# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ec6b402b1474f8a66c707656e01cdd0e79fe3e8f4a3fee48d7bf5e8a8f1d50716d0c510847db59b432069db35af7e5c55e41de014581ba11cc5fee70ed8f0cc

test:
  secret_key_base: 85cbff72974f61762dc9b91065921f0daaad5248b10e8073859421a78d81fb2d36ff957016c594b80904f7c77fb89cd073ce5314c1deaa68b219a8b0a95e5fbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
